name: spot
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  camera: ^0.8.0
  flutter_bloc: ^7.0.0-nullsafety.3
  intl: ^0.17.0
  shared_preferences: ^2.0.3
  google_maps_flutter: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0-nullsafety.2
  mocktail: 0.0.1-dev.12
  very_good_analysis: ^2.0.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true
  generate: true
